spring:
  datasource:
    url: jdbc:mysql://124.223.99.166:3306/demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: L200107208017./@
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ThisIsADemo
server:
  port: 9998

logging:
  level:
    com.example.demo: debug

mybatis:
  mapper-locations: classpath:mapper/**/*.xml  # ??????